### ISSUE TITLE
List<Edge> never gets filled

### ISSUE THREAD

**Issue by nickmansrob** [nickmansrob/Followtrack#1]
*At L85 the edgeList, which is passed into the parseJson() method as a new ArrayList<>(), doesn't get filled with the response data from Volley. As a consequence the while loop becomes infinite.*

### Cause
The StringRequest is processed in a lamba expression which requires a static or final value to be passed into. As the edgeList can't be one of those, lamba can't access it.

Need to figure out how to pass in the List<Edge> without making it a global variable to avoid leaks so getters and setters can't be used.

**Comment by ErikDuysters** [comment]
jsonResponse.getData().getUser().getEdgeFollowedBy().getEdges() returns a List. I'm not sure, but the add function does it also accepts a list or does it only accepts an element in that list?
